### ISSUE TITLE
Add optional template_name parameter for the POST /invoice endpoint to specify a different template for the invoicing rules.

### ISSUE THREAD

**Issue by adrianmoloce** [quick-invoice-api/invoice-utils#18]
Extend the POST /invoice endpoint with an optional {template_name} parameter. This parameter is given to the engine when processing the invoice or to the PDFInvoiceRenderer when rendering the invoice content? Logic in code seems to be consistent with the second. Otherwise there seem to be different templates types in the code, which could be named accordingly.
If the given template_name does not exist, use a default system configured one.
If the system configured template does not exist, default to one that is for sure?

**Comment by koosie0507** [comment]
There are two types of templates used for rendering an invoice:
- the template containing the rules by which the invoice data is constructed
- the reporting template that provides the layout and styling for the PDF that is generated.

Indeed, there should be a parameter reflecting each of these templates. Let's call the first one the `ruleTemplate` and the second one the `reportType`. Because the reporting template is actually made up of multiple files (Jinja + CSS), let's leave the `reportType` parameter out of the conversation for this question. Let's focus on the `ruleTemplate` for now (which is just a JSON file).

The `ruleTemplate` that will always be included with the `invoice-utils` package is called `basic.json` and sits at the root of the package (`src/invoice_utils`). By default, the system configuration points to this file. If the file does not exist, we should fail starting the API. To accomplish that and much more, let's have a look at [managing settings with Pydantic](https://docs.pydantic.dev/latest/concepts/pydantic_settings/).

**Comment by adrianmoloce** [comment]
Alright, so there are 3 types of templates so far:

-  ruleTemplate
-  reportType
-  MailBodyTemplate

I think there might be a logic error with this line then. It uses a default MailBodyTemplate but the code is meant to work with ruleTemplates. #15, [code bit](https://github.com/quick-invoice-api/invoice-utils/blob/eda2f84d7d2eec6accb7b2a7d295a8674b4a1c05/src/invoice_utils/depends.py#L8), [code for html template ](https://github.com/quick-invoice-api/invoice-utils/blob/eda2f84d7d2eec6accb7b2a7d295a8674b4a1c05/src/invoice_utils/templates/default_template.html).
If so, should I change it to point to basic.json as part of this issue?

**Comment by adrianmoloce** [comment]
> Alright, so there are 3 types of templates so far:
> 
> * ruleTemplate
> * reportType
> * MailBodyTemplate
> 
> I think there might be a logic error with this line then. It uses a default MailBodyTemplate but the code is meant to work with ruleTemplates. #15, [code bit](https://github.com/quick-invoice-api/invoice-utils/blob/eda2f84d7d2eec6accb7b2a7d295a8674b4a1c05/src/invoice_utils/depends.py#L8), [code for html template ](https://github.com/quick-invoice-api/invoice-utils/blob/eda2f84d7d2eec6accb7b2a7d295a8674b4a1c05/src/invoice_utils/templates/default_template.html). If so, should I change it to point to basic.json as part of this issue?

On second thought, the only "problem" with this is that we use the same directory for both kinds of templates, perhaps just a renaming of the env variable will suffice.

DEFAULT_BODY_TEMPLATE_DIRECTORY -> DEFAULT_TEMPLATES_DIRECTORY

**Comment by adrianmoloce** [comment]
> Extend the POST /invoice endpoint with an optional {template_name} parameter. This parameter is given to the engine when processing the invoice or to the PDFInvoiceRenderer when rendering the invoice content? Logic in code seems to be consistent with the second. Otherwise there seem to be different templates types in the code, which could be named accordingly. If the given template_name does not exist, use a default system configured one. If the system configured template does not exist, default to one that is for sure?

At least for the send_mail flag and address params, those are sent thru the request body, shouldn't we do the same for rule_template_name? rather than `POST /invoice?rule_template_name=template_name` ?

**Comment by koosie0507** [comment]
```
POST /invoice
{
  "ruleTemplate": "a_value"
}
```
should run repo.get_by_key("a_value"), where repo is whatever `depends.template_repo()` returns. I hope it's clear enough now.
